### ISSUE TITLE
ShellCheck errors - Improve Pipeline

### ISSUE THREAD

**Issue by mgrottenthaler** [stereum-dev/stereum-sba-audit-2021#2]
Currently there are a few ShellCheck (<https://github.com/koalaman/shellcheck>) errors:

``` bash
./ethereum2-docker-compose/edc-up.sh:3:38: warning: Use "$@" (with quotes) to prevent whitespace problems. [SC2048]
./ethereum2-docker-compose/edc-up.sh:3:38: note: Double quote to prevent globbing and word splitting. [SC2086]
./ethereum2-docker-compose/edc-restart.sh:3:21: warning: Use "$@" (with quotes) to prevent whitespace problems. [SC2048]
./ethereum2-docker-compose/edc-restart.sh:3:21: note: Double quote to prevent globbing and word splitting. [SC2086]
./ethereum2-docker-compose/edc-restart.sh:3:64: warning: Use "$@" (with quotes) to prevent whitespace problems. [SC2048]
./ethereum2-docker-compose/edc-restart.sh:3:64: note: Double quote to prevent globbing and word splitting. [SC2086]
./ethereum2-docker-compose/edc-stop.sh:3:21: warning: Use "$@" (with quotes) to prevent whitespace problems. [SC2048]
./ethereum2-docker-compose/edc-stop.sh:3:21: note: Double quote to prevent globbing and word splitting. [SC2086]
```

We recommend to implement a Pipeline to run ShellCheck on every commit. This can for example be accomplished with this GitHub Action: <https://github.com/marketplace/actions/shellcheck>

**Comment by stefa2k** [comment]
Do you recommend it on all repositories or only specific ones?

**Comment by mgrottenthaler** [comment]
I would at least use ShellCheck in every repository that has shell script files in it. It is a very simple, fast check.

**Comment by stefa2k** [comment]
Done, only in https://github.com/stereum-dev/ethereum2-control-center-cli errors left.

@gbayasgalan can you take care of these issues? https://github.com/stereum-dev/ethereum2-control-center-cli/runs/3672750524

**Comment by gbayasgalan** [comment]
> Done, only in https://github.com/stereum-dev/ethereum2-control-center-cli errors left.
> 
> @gbayasgalan can you take care of these issues? https://github.com/stereum-dev/ethereum2-control-center-cli/runs/3672750524

yes of course, I'll take care of it

**Comment by gbayasgalan** [comment]
done! PR: https://github.com/stereum-dev/ethereum2-control-center-cli/pull/52

**Comment by mgrottenthaler** [comment]
verified! ShellCheck pipeline is now implemented in the following repos:

* https://github.com/stereum-dev/ethereum2-docker-compose/blob/master/.github/workflows/main.yml
* https://github.com/stereum-dev/ethereum2-ansible/blob/main/.github/workflows/main.yml
