### ISSUE TITLE
SSH Config: Replace RSA with Ed25519

### ISSUE THREAD

**Issue by FWieshaider** [stereum-dev/stereum-sba-audit-2021#5]
We recommend to use a modern public-key algorithm instead of RSA.

Further information: https://blog.peterruppel.de/ed25519-for-ssh/

**Comment by stefa2k** [comment]
Is this about the connection from the controlcenter-container to the docker host?

**Comment by FWieshaider** [comment]
No, this is about the key that gets generated in [this](https://github.com/stereum-dev/ethereum-setup/blob/da188bb723436e4a9c2b14537159f7657833d038/base-installer/roles/stereum-base/tasks/setup-users.yml#L7) ansible file.

**Comment by stefa2k** [comment]
Thanks, this is used for connecting from the cc-container to the docker host: https://github.com/stereum-dev/ethereum-setup/blob/da188bb723436e4a9c2b14537159f7657833d038/base-installer/roles/stereum-controlcenter/templates/docker-compose.yaml#L11

**Comment by stefa2k** [comment]
using ed25519 now instead of rsa

tested and working
