### ISSUE TITLE
Path Traversal over API Endpoint

### ISSUE THREAD

**Issue by FWieshaider** [stereum-dev/stereum-sba-audit-2021#7]
The API endpoint in _ethereum2-control-center-web_ receives requests from _electron-launcher_, for example:
```
POST /api/setup/start HTTP/1.1
Host: localhost:8081
Cache-Control: max-age=0
Content-Length: 97

{
    "inventory": "inventory.yaml",
    "playbook": "restart-host.yaml",
    "extra_vars": {},
    "extraVars": {}
}
```
It is possible to change the attribute "playbook" to another file, for example "../../../../../../etc/shadow" and retrieve a part of the file's content:
```
HTTP/1.1 500 Internal Server Error
date: Wed, 22 Sep 2021 10:58:47 GMT
server: uvicorn
content-length: 330
content-type: application/json
Connection: close

{
    "detail": "A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead\n\nThe error appears to be in '/etc/shadow': line 1, column 1, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\nroot:*:18725:0:99999:7:::\n^ here\n"
}
```
The error message contains a line of the shadow file, which also shows that the web server has permissions to access the file.
Whitelisting solution should be implemented on the server, which allows only allowed user input.
File names should not be passed at this point, as they may tempt an attacker to change them.
Calling functions or function IDs would be a better solution.

**Comment by sapien99** [comment]
ist kein problem, fix ich gleich. Wollen wir das konfigurierbar oder fest verdrahtet im docker image? (btw. der angesprochene root-user ist der root-user im container, NICHT der des docker-hosts)

**Comment by sapien99** [comment]
eine variante wäre zb. die angesprochenen ids - mit einem mapping file das wir von aussen mounten. eine andere variante das strippen der pfade und erlaubte playbook-namen, eine dritte gar keinen playbook namen sondern fix bzw. nur über mount mitgegeben

**Comment by sapien99** [comment]
fix committed as https://github.com/stereum-dev/ethereum2-control-center-web/commit/24f594b486aafbb08cfa1e41d311fb0c5b9697e2

**Comment by sapien99** [comment]
ready for next release

**Comment by FWieshaider** [comment]
verified! A generic error message gets now returned.
